#! /bin/bash

# Variables

datapath=/pub61/florat/velocity/aphantopus_hyperantus/modern_data/00_raw_reads_modc
output=/pub64/mattm/velocity/sequence_files/Aphantopus_hyperantus/modc_test3
threads=32
remove_temp=true
PICARD=/pub64/mattm/apps/picard/build/libs/picard.jar
RGID=E3modc
RGLB=mod03
logfile=Ah_mode_bamprep.log




# Code

# Set up log file

exec 3>&1 1>"$logfile" 2>&1
trap "echo 'ERROR: An error occurred during execution, check log $logfile for details.' >&3" ERR
trap '{ set +x; } 2>/dev/null; echo -n "[$(date -Is)]  "; set -x' DEBUG
set -e

# Process bams

mkdir -p $output

for file in "$datapath"/*sort.bam; do 
filename=${file##*/}
filetag=$(basename "$filename" ".sort.bam")


echo "Moving to sample ${filetag}" | tee /dev/fd/3

sleep 3

echo "Adding read groups" | tee /dev/fd/3

java -jar $PICARD AddOrReplaceReadGroups \
-I $file \
-O "$output/${filetag}.RG.bam" \
-RGID $RGID \
-RGLB $RGLB \
-RGPL ILLUMINA -RGPU unit1 \
-RGSM $filetag

echo "Filtering by flags" | tee /dev/fd/3

samtools view -@ 32 -b -f 3 -F 3852 "$output/${filetag}.RG.bam" -o "$output/${filetag}.filtered.bam"

echo "Sorting by name" | tee /dev/fd/3

samtools sort -@ 32 -n "$output/${filetag}.filtered.bam" -o "$output/${filetag}.sorted.n.bam"

echo "Adding mate score tag" | tee /dev/fd/3

samtools fixmate -@ 32 -m "$output/${filetag}.sorted.n.bam" "$output/${filetag}.fixmate.bam"

echo "Sorting by position" | tee /dev/fd/3

samtools sort -@ 32 "$output/${filetag}.fixmate.bam" -o "$output/${filetag}.sorted.p.bam"

echo "Removing duplicate reads" | tee /dev/fd/3

samtools markdup -r -@ 32 "$output/${filetag}.sorted.p.bam" "$output/${filetag}.markdup.bam"

echo "Indexing output bam" | tee /dev/fd/3

samtools index "$output/${filetag}.markdup.bam"

if $remove_temp; then
  rm "$output/${filetag}.sorted.n.bam" "$output/${filetag}.fixmate.bam" "$output/${filetag}.sorted.p.bam" "$output/${filetag}.filtered.bam" "$output/${filetag}.RG.bam"
fi

done

echo "Finished!" | tee /dev/fd/3






#! /bin/bash 

# conda activate java8 (conda install cidermole::jdk8)

java -jar /pub64/mattm/apps/java/GenomeAnalysisTK.jar \
-T RealignerTargetCreator \
-R /pub64/mattm/velocity/sequence_files/Aphantopus_hyperantus/reference/GCA_902806685_noW.fa \
-o AH-01-2016-01.intervals \
-I AH-01-2016-01.markdup.bam

java -jar /pub64/mattm/apps/java/GenomeAnalysisTK.jar \
-T IndelRealigner \
-R /pub64/mattm/velocity/sequence_files/Aphantopus_hyperantus/reference/GCA_902806685_noW.fa \
-targetIntervals AH-01-2016-01.intervals \
-I AH-01-2016-01.markdup.bam \
-o AH-01-2016-01.realn.bam


#! /bin/bash

echo -e "AH-01-2016-01.realn.bam\tpaired\t151" > readgroups.txt

atlas mergeOverlappingReads  --bam AH-01-2016-01.realn.bam --readGroupSettings readgroups.txt

atlas estimateErrors --bam AH-01-2016-01.realn_merged.bam \
--fasta ~/velocity/sequence_files/Aphantopus_hyperantus/reference/GCA_902806685_noW.fa \
--Npsi 0 --out AH-01-2016-01.EE
