#! /bin/bash

# Variables

datapath=/pub61/florat/velocity/aphantopus_hyperantus/modern_data/00_raw_reads_modc
output=/pub64/mattm/velocity/sequence_files/Aphantopus_hyperantus/modc_test3
threads=32
remove_temp=true
PICARD=/pub64/mattm/apps/picard/build/libs/picard.jar
RGID=E3modc
RGLB=mod03


# Code

mkdir -p $output

for file in "$datapath"/*sort.bam; do 
filename=${file##*/}
filetag=$(basename "$filename" ".sort.bam")
echo $filename
echo $filetag

sleep 5

echo "adding read groups"

sleep 5

java -jar $PICARD AddOrReplaceReadGroups \
-I $file \
-O "$output/${filetag}.RG.bam" \
-RGID $RGID \
-RGLB $RGLB \
-RGPL ILLUMINA -RGPU unit1 \
-RGSM $filetag

echo "filtering by flags"

samtools view -@ 32 -b -f 3 -F 3852 "$output/${filetag}.RG.bam" -o "$output/${filetag}.filtered.bam"

echo "sorting by name"

samtools sort -@ 32 -n "$output/${filetag}.filtered.bam" -o "$output/${filetag}.sorted.n.bam"

echo "Adding mate score tag"

samtools fixmate -@ 32 -m "$output/${filetag}.sorted.n.bam" "$output/${filetag}.fixmate.bam"

echo "Sorting by position"

samtools sort -@ 32 "$output/${filetag}.fixmate.bam" -o "$output/${filetag}.sorted.p.bam"

echo "removing duplicate reads"

samtools markdup -r -@ 32 "$output/${filetag}.sorted.p.bam" "$output/${filetag}.markdup.bam"

echo "indexing output bam"

samtools index "$output/${filetag}.markdup.bam"

echo "done"

sleep 5

if $remove_temp; then
  rm "$output/${filetag}.sorted.n.bam" "$output/${filetag}.fixmate.bam" "$output/${filetag}.sorted.p.bam" "$output/${filetag}.filtered.bam" "$output/${filetag}.RG.bam"
fi

done








#! /bin/bash 

# conda activate java8 (conda install cidermole::jdk8)

java -jar /pub64/mattm/apps/java/GenomeAnalysisTK.jar \
-T RealignerTargetCreator \
-R /pub64/mattm/velocity/sequence_files/Aphantopus_hyperantus/reference/GCA_902806685_noW.fa \
-o AH-01-2016-01.intervals \
-I AH-01-2016-01.markdup.bam

java -jar /pub64/mattm/apps/java/GenomeAnalysisTK.jar \
-T IndelRealigner \
-R /pub64/mattm/velocity/sequence_files/Aphantopus_hyperantus/reference/GCA_902806685_noW.fa \
-targetIntervals AH-01-2016-01.intervals \
-I AH-01-2016-01.markdup.bam \
-o AH-01-2016-01.realn.bam


#! /bin/bash

echo -e "AH-01-2016-01.realn.bam\tpaired\t151" > readgroups.txt

atlas mergeOverlappingReads  --bam AH-01-2016-01.realn.bam --readGroupSettings readgroups.txt

atlas estimateErrors --bam AH-01-2016-01.realn_merged.bam \
--fasta ~/velocity/sequence_files/Aphantopus_hyperantus/reference/GCA_902806685_noW.fa \
--Npsi 0 --out AH-01-2016-01.EE
